project_name: reinforcer
before:
  hooks:
    - go mod download

builds:
  - binary: reinforcer
    main: ./cmd/reinforcer/main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/clear-street/reinforcer/cmd/reinforcer/cmd.Version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksum.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc

dockers:
  - goos: linux
    goarch: amd64
    ids:
      - reinforcer
    image_templates:
      - 'clear-street/reinforcer:{{ .Tag }}'
      - 'clear-street/reinforcer:v{{ .Major }}'
      - 'clear-street/reinforcer:v{{ .Major }}.{{ .Minor }}'
      - 'clear-street/reinforcer:latest'
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"

brews:
  - homepage: https://github.com/clear-street/reinforcer
    description: "Codegen tool for easy adoption of resiliency patterns in Go"
    tap:
      owner: clear-street
      name: homebrew-reinforcer
    folder: Formula
    test: |
      system "#{bin}/reinforcer --version"
